ADJECTIVES = [
    "infected",
    "swollen",
    "misaligned",
    "ruptured",
    "fused",
    "congenital",
    "diseased",
    "missing",
    "smelly",
    "severed",
    "crushed",
    "dislocated",
    "mangled",
    "icky",
    "unrecognizable",
    "contorted",
    "bloated",
    "botched",
    "oozing",
    "hairy",
    "dicey",
    "deteriorated",
    "unadvisable",
    "experimental",
    "unforeseen",
    "remarkable",
    "unprecedented",
    "unpredictable",
    "questionable",
]

BODY_PARTS = [
    "brain",
    "eyeball",
    "nostril",
    "mouth",
    "testicle",
    "butt",
    "rectal",
    "hand",
    "foot",
    "consciousness",
    "nipple",
    "pinky toe",
    "belly button",
    "spinal",
    "urethral",
    "armpit",
    "skin",
    "tongue",
    "tooth",
    "ear lobe",
    "liver",
    "humor",
    "blood",
    "lymph"
]

PROCEDURES = [
    "removal",
    "lobotomy",
    "replacement",
    "transplant",
    "examination",
    "expansion",
    "reinforcement",
    "bifurcation",
    "blast",
    "tweak",
    "rearrangement",
    "perforation",
    "abrasion",
    "reduction",
    "reconstruction",
    "augmentation",
    "peel",
    "fusion",
    "psychotherapy",
    "group therapy",
    "hypnotism",
    "regression therapy",
    "vaccination",
    "leeching",
    "x-ray",
    "radiation",
    "Pasteurization",
    "anesthesia",
    "leeching",
    "phrenology chart",
    "purge",
    "elixir treatment",
    "gas treatment",
    "bloodletting",
    "cold douche",
    "smoke inhalation"
]