# Generated by Django 4.2.5 on 2023-10-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.CharField(max_length=132)),
                ('post_date', models.DateTimeField(verbose_name='time posted')),
            ],
        ),
    ]
